### ISSUE TITLE
07-31-2021 data missing

### ISSUE THREAD

**Issue by ningkko** [lopezbec/COVID19_Tweets_Dataset#1]
This shows 404
https://raw.githubusercontent.com/lopezbec/COVID19_Tweets_Dataset/master/Summary_Details/2021_07/2021_07_31_23_Summary_Details.csv

**Comment by lopezbec** [comment]
Thanks for bringing this to our attention. The files for 2021_07_31 are not on the repo. We are currently working on getting the NER and NER_ES files for that day as well (it should be up by tomorrow).
