### ISSUE TITLE
Missing data at 2020-10-31

### ISSUE THREAD

**Issue by jiesutd** [lopezbec/COVID19_Tweets_Dataset#7]
Hi Lopez,

Thanks for sharing this great project! 

I noticed that the data at 2020-10-31 is missed (https://github.com/lopezbec/COVID19_Tweets_Dataset/tree/master/Summary_Details/2020_10) is it possible the add it back?

**Comment by lopezbec** [comment]
Thanks for catching this! We will work on getting them back. I will close the issue once resolved.

**Comment by lopezbec** [comment]
The data is now in the repo. Once again, thanks for letting us know!
